import type { AppSyncResolverHandler } from 'aws-lambda';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import {
  DynamoDBDocumentClient,
  ScanCommand,
  UpdateCommand,
  PutCommand,
  GetCommand,
} from '@aws-sdk/lib-dynamodb';
import { randomUUID } from 'node:crypto';

const ddb = DynamoDBDocumentClient.from(new DynamoDBClient());

// Injected by the Amplify backend at deploy time (see amplify/backend.ts).
const INVITE_TABLE_NAME = process.env.INVITE_TABLE_NAME!;
const FAMILY_MEMBER_TABLE_NAME = process.env.FAMILY_MEMBER_TABLE_NAME!;
const FAMILY_TABLE_NAME = process.env.FAMILY_TABLE_NAME!;

interface RedeemInviteArgs {
  token: string;
}

interface RedeemInviteResult {
  familyId: string;
  familyName: string;
  role: string;
}

/**
 * AppSync Lambda resolver for the `redeemInvite` custom mutation.
 *
 * Enforces:
 *   1. Caller must be authenticated (identity resolved from AppSync context).
 *   2. Token must map to a PENDING invite that has not expired.
 *   3. Invite email must match the caller's email (prevents link forwarding abuse).
 *   4. Idempotent: if the caller is already a member of the family the invite
 *      refers to, the existing membership is returned without error.
 */
export const handler: AppSyncResolverHandler<RedeemInviteArgs, RedeemInviteResult> = async (
  event
) => {
  const { token } = event.arguments;

  if (!token || !token.trim()) {
    throw new Error('token is required.');
  }

  // ── 1. Resolve caller identity ─────────────────────────────────────────────
  const identity = event.identity as Record<string, any> | null;
  const callerEmail: string | null =
    identity?.username ?? identity?.claims?.email ?? null;
  if (!callerEmail) {
    throw new Error('Unauthorized: No identity found.');
  }

  // ── 2. Look up the invite by token ─────────────────────────────────────────
  // Using Scan with a filter expression because the GSI name generated by
  // Amplify Gen 2 is not deterministically available at runtime without
  // injecting it as an environment variable.  Invite tables are small (one
  // record per invited person), so a full-table Scan is acceptable here.
  const inviteResult = await ddb.send(
    new ScanCommand({
      TableName: INVITE_TABLE_NAME,
      FilterExpression: '#token = :token',
      ExpressionAttributeNames: { '#token': 'token' },
      ExpressionAttributeValues: { ':token': token.trim() },
    })
  );

  const invite = inviteResult.Items?.[0];
  if (!invite) {
    throw new Error('Invalid invite token.');
  }

  // ── 3. Validate invite status and expiry ───────────────────────────────────
  if (invite.status !== 'PENDING') {
    throw new Error('This invite has already been used or is no longer valid.');
  }

  if (new Date(invite.expiresAt) < new Date()) {
    throw new Error('This invite has expired. Please ask the family admin to resend the invite.');
  }

  // ── 4. Verify invite email matches caller ──────────────────────────────────
  if (invite.email.toLowerCase() !== callerEmail.toLowerCase()) {
    throw new Error('This invite was not issued to your email address.');
  }

  // ── 5. Check for existing membership (idempotency) ─────────────────────────
  const existingResult = await ddb.send(
    new ScanCommand({
      TableName: FAMILY_MEMBER_TABLE_NAME,
      FilterExpression: 'userId = :userId AND familyId = :familyId',
      ExpressionAttributeValues: {
        ':userId': callerEmail,
        ':familyId': invite.familyId,
      },
    })
  );

  // ── 6. Fetch family name ───────────────────────────────────────────────────
  const familyResult = await ddb.send(
    new GetCommand({
      TableName: FAMILY_TABLE_NAME,
      Key: { id: invite.familyId },
    })
  );
  const familyName: string = familyResult.Item?.name ?? 'Your Family';

  if (existingResult.Items && existingResult.Items.length > 0) {
    // Already a member — return existing membership without error.
    const existing = existingResult.Items[0];
    return {
      familyId: invite.familyId,
      familyName,
      role: existing.role ?? invite.role,
    };
  }

  // ── 7. Create the FamilyMember record ──────────────────────────────────────
  const memberId = randomUUID();
  const now = new Date().toISOString();

  await ddb.send(
    new PutCommand({
      TableName: FAMILY_MEMBER_TABLE_NAME,
      Item: {
        id: memberId,
        familyId: invite.familyId,
        userId: callerEmail,
        role: invite.role,
        displayName: null,
        createdAt: now,
        updatedAt: now,
        __typename: 'FamilyMember',
      },
      ConditionExpression: 'attribute_not_exists(id)',
    })
  );

  // ── 8. Mark the invite as ACCEPTED ─────────────────────────────────────────
  await ddb.send(
    new UpdateCommand({
      TableName: INVITE_TABLE_NAME,
      Key: { id: invite.id },
      UpdateExpression: 'SET #status = :status, updatedAt = :now',
      ExpressionAttributeNames: { '#status': 'status' },
      ExpressionAttributeValues: {
        ':status': 'ACCEPTED',
        ':now': now,
      },
    })
  );

  return {
    familyId: invite.familyId,
    familyName,
    role: invite.role,
  };
};
