# Generated by Django 5.2.16 on 2026-07-19 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0002_add_family_account_fk'),
        ('core', '0004_familyaccount_onboarding_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCalendarFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('outlook', 'Outlook')], max_length=10)),
                ('ical_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_feeds', to='core.familyaccount')),
            ],
        ),
    ]
