# Generated by Django 5.2.16 on 2026-07-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0003_externalcalendarfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcalendarfeed',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalcalendarfeed',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
