# Generated by Django 5.2.17 on 2026-09-26 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_events", "0004_externalcalendarfeed_last_checked_at_and_more"),
        ("core", "0005_emailverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_events",
                to="core.familyaccount",
            ),
        ),
    ]
