# Generated by Django 4.2.25 on 2026-07-13 21:06

from django.db import migrations


def backfill_account(apps, schema_editor):
    FamilyAccount = apps.get_model("core", "FamilyAccount")
    FamilyMembership = apps.get_model("core", "FamilyMembership")
    User = apps.get_model("auth", "User")

    owner = User.objects.filter(is_superuser=True).order_by("id").first()
    if owner is None:
        owner = User.objects.order_by("id").first()
    if owner is None:
        # No users exist yet (fresh/empty database) — nothing to backfill.
        return

    account, _ = FamilyAccount.objects.get_or_create(
        owner=owner,
        defaults={"name": "My Family", "slug": "my-family"},
    )
    FamilyMembership.objects.get_or_create(
        account=account, user=owner, defaults={"role": "owner"},
    )

    model_paths = [
        ("vehicles", "Vehicle"),
        ("property", "Property"),
        ("calendar_events", "CalendarEvent"),
        ("vacations", "Vacation"),
        ("cookbook", "Recipe"),
        ("shopping", "ShoppingItem"),
        ("tasks", "FamilyTask"),
    ]
    for app_label, model_name in model_paths:
        Model = apps.get_model(app_label, model_name)
        Model.objects.filter(account__isnull=True).update(account=account)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_add_family_account_fk"),
        ("vehicles", "0003_add_family_account_fk"),
        ("property", "0008_add_family_account_fk"),
        ("calendar_events", "0002_add_family_account_fk"),
        ("vacations", "0003_add_family_account_fk"),
        ("cookbook", "0002_add_family_account_fk"),
        ("shopping", "0003_add_family_account_fk"),
        ("tasks", "0002_add_family_account_fk"),
    ]

    operations = [
        migrations.RunPython(backfill_account, migrations.RunPython.noop),
    ]
