# Generated by Django 5.2.16 on 2026-07-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_backfill_founding_family_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyaccount',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('family', 'Family')], default='free', max_length=10),
        ),
    ]
