# Generated by Django 5.2.16 on 2026-07-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_familyaccount_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyaccount',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
