# Generated by Django 5.2.17 on 2026-09-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_emailverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("member", "Member"),
                    ("student", "Student"),
                ],
                default="member",
                max_length=10,
            ),
        ),
    ]
