# Generated by Django 5.2.17 on 2026-09-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="familyaccount",
            name="email_weekly_digest",
            field=models.BooleanField(
                default=True,
                help_text="Send the account owner a weekly email summarizing overdue tasks and upcoming maintenance (#384).",
            ),
        ),
    ]
