# Generated by Django 5.2.17 on 2026-09-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_familyaccount_email_weekly_digest"),
        ("core", "0006_userprofile"),
    ]

    operations = []
