# Generated by Django 5.2.17 on 2026-09-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_familymembership_role"),
        ("core", "0007_merge_0006_familyaccount_email_weekly_digest_0006_userprofile"),
    ]

    operations = []
