# Generated by Django 4.2.25 on 2026-06-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='planning', max_length=20)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VacationExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('FOOD', 'Food'), ('TRANSPORT', 'Transport'), ('ACTIVITY', 'Activity'), ('SHOPPING', 'Shopping'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_by', models.CharField(max_length=100)),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='vacations.vacation')),
            ],
            options={
                'ordering': ['date', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('CAR', 'Car Rental'), ('OTHER', 'Other')], max_length=20)),
                ('provider', models.CharField(max_length=200)),
                ('confirmation_number', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='vacations.vacation')),
            ],
            options={
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='vacations.vacation')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
