# Generated by Django 5.2.17 on 2026-09-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cookbook", "0003_alter_recipe_account"),
        ("cookbook", "0003_mealplan"),
    ]

    operations = []
