# Generated by Django 4.2.25 on 2026-07-13 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_family_account_fk'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytask',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.familyaccount'),
        ),
        migrations.AddField(
            model_name='historicalfamilytask',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.familyaccount'),
        ),
    ]
