# Generated by Django 5.2.17 on 2026-09-26 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_emailverification"),
        ("tasks", "0002_add_family_account_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familytask",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="core.familyaccount",
            ),
        ),
    ]
