import type { AppSyncResolverHandler } from 'aws-lambda';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import {
  DynamoDBDocumentClient,
  GetCommand,
  ScanCommand,
  UpdateCommand,
  TransactWriteCommand,
} from '@aws-sdk/lib-dynamodb';

const ddb = DynamoDBDocumentClient.from(new DynamoDBClient());

// Injected by the Amplify backend at deploy time (see amplify/backend.ts).
const TABLE_NAME = process.env.FAMILY_MEMBER_TABLE_NAME!;

const VALID_ROLES = ['ADMIN', 'PLANNER', 'MEMBER'] as const;
type FamilyRole = (typeof VALID_ROLES)[number];

interface UpdateMemberRoleArgs {
  memberId: string;
  newRole: string;
}

interface MemberItem {
  id: string;
  familyId: string;
  userId: string;
  role: FamilyRole;
  displayName?: string;
}

/**
 * AppSync Lambda resolver for the `updateMemberRole` custom mutation.
 *
 * Enforces:
 *   1. Valid role value check.
 *   2. Privilege-escalation protection – caller must be ADMIN.
 *   3. Cross-family protection – caller and target must share the same familyId.
 *   4. Last-admin guard – the final ADMIN in a family may not be demoted.
 *      Implemented with TransactWriteItems to prevent the race condition where
 *      two admins demote themselves simultaneously.
 */
export const handler: AppSyncResolverHandler<UpdateMemberRoleArgs, MemberItem> = async (
  event
) => {
  const { memberId, newRole } = event.arguments;

  // ── 1. Validate the requested role ────────────────────────────────────────
  if (!(VALID_ROLES as readonly string[]).includes(newRole)) {
    throw new Error(`Invalid role: ${newRole}`);
  }

  // ── 2. Resolve caller identity from AppSync context ───────────────────────
  // With Amplify Gen 2 email-based auth, event.identity.username equals the
  // Cognito username (email address), matching the userId stored in FamilyMember.
  const identity = event.identity as Record<string, any> | null;
  const callerUsername =
    identity?.username ?? identity?.claims?.email ?? null;
  if (!callerUsername) {
    throw new Error('Unauthorized: No identity found.');
  }

  // ── 3. Look up the target member by primary key ───────────────────────────
  const targetResult = await ddb.send(
    new GetCommand({
      TableName: TABLE_NAME,
      Key: { id: memberId },
    })
  );
  const targetMember = targetResult.Item as MemberItem | undefined;
  if (!targetMember) {
    throw new Error('Member not found.');
  }

  // ── 4. Look up the caller's FamilyMember record ────────────────────────────
  // DynamoDB Scan with a userId filter is used here because the GSI index name
  // generated by Amplify Gen 2 is not deterministically available at runtime
  // without injecting it as an environment variable via backend.ts.  For a
  // family app with a small per-family member count (<100), this Scan is both
  // fast and cost-effective.  The userId-index GSI defined on the model means
  // this query benefits from the index at the AppSync/GraphQL layer; a future
  // optimisation can inject the GSI name and switch to QueryCommand here.
  const callerResult = await ddb.send(
    new ScanCommand({
      TableName: TABLE_NAME,
      FilterExpression: 'userId = :userId',
      ExpressionAttributeValues: { ':userId': callerUsername },
    })
  );
  const callerMember = callerResult.Items?.[0] as MemberItem | undefined;
  if (!callerMember) {
    throw new Error('Unauthorized: Caller has no family membership.');
  }

  // ── 5. Privilege-escalation protection ────────────────────────────────────
  if (callerMember.role !== 'ADMIN') {
    throw new Error('Unauthorized: Only admins can update member roles.');
  }

  // ── 6. Cross-family protection ────────────────────────────────────────────
  if (targetMember.familyId !== callerMember.familyId) {
    throw new Error('Unauthorized: Cannot update members from a different family.');
  }

  // ── 7. Last-admin guard: atomic demotion via TransactWriteItems ──────────
  if (targetMember.role === 'ADMIN' && newRole !== 'ADMIN') {
    // Find all ADMIN members in the family to enforce last-admin protection.
    // A Query on a familyId GSI would be more efficient at scale; the
    // familyId-index GSI defined in the schema supports this optimisation.
    // Family member tables are small (<100 rows per family), so Scan is fine.
    const adminScanResult = await ddb.send(
      new ScanCommand({
        TableName: TABLE_NAME,
        FilterExpression: 'familyId = :familyId AND #role = :admin',
        ExpressionAttributeNames: { '#role': 'role' },
        ExpressionAttributeValues: {
          ':familyId': callerMember.familyId,
          ':admin': 'ADMIN',
        },
      })
    );
    const adminMembers = (adminScanResult.Items ?? []) as MemberItem[];

    if (adminMembers.length <= 1) {
      throw new Error('A family must have at least one administrator.');
    }

    // Pick any other admin (not the target) as the anchor for the condition
    // check.  If no other admin is found treat the target as the last admin.
    const otherAdmin = adminMembers.find((m) => m.id !== memberId);
    if (!otherAdmin) {
      throw new Error('A family must have at least one administrator.');
    }

    // Perform the role update as a DynamoDB transaction so the last-admin
    // check and the write are atomic.  The ConditionCheck on otherAdmin
    // guarantees that, at commit time, another ADMIN still exists in the
    // family.  This prevents the race condition where two admins call this
    // mutation concurrently: only one transaction can commit; the second will
    // fail because the ConditionCheck will no longer hold after the first
    // transaction changes otherAdmin's role (or the Update condition on the
    // target fails if the target's role was already changed).
    try {
      await ddb.send(
        new TransactWriteCommand({
          TransactItems: [
            {
              // Verify at commit time that another ADMIN still exists.
              ConditionCheck: {
                TableName: TABLE_NAME,
                Key: { id: otherAdmin.id },
                ConditionExpression: '#role = :admin',
                ExpressionAttributeNames: { '#role': 'role' },
                ExpressionAttributeValues: { ':admin': 'ADMIN' },
              },
            },
            {
              // Apply the role update only if the target is still ADMIN
              // (optimistic-lock guard against concurrent mutations).
              Update: {
                TableName: TABLE_NAME,
                Key: { id: memberId },
                UpdateExpression: 'SET #role = :newRole',
                ConditionExpression: '#role = :currentRole',
                ExpressionAttributeNames: { '#role': 'role' },
                ExpressionAttributeValues: {
                  ':newRole': newRole,
                  ':currentRole': 'ADMIN',
                },
              },
            },
          ],
        })
      );
    } catch (err: any) {
      if (err.name === 'TransactionCanceledException') {
        throw new Error('A family must have at least one administrator.');
      }
      throw err;
    }

    return {
      id: memberId,
      familyId: targetMember.familyId,
      userId: targetMember.userId,
      role: newRole as FamilyRole,
      displayName: targetMember.displayName ?? undefined,
    };
  }

  // ── 8. Apply the role update (non-admin-demotion cases) ───────────────────
  await ddb.send(
    new UpdateCommand({
      TableName: TABLE_NAME,
      Key: { id: memberId },
      UpdateExpression: 'SET #role = :newRole',
      ExpressionAttributeNames: { '#role': 'role' },
      ExpressionAttributeValues: { ':newRole': newRole },
    })
  );

  return {
    id: memberId,
    familyId: targetMember.familyId,
    userId: targetMember.userId,
    role: newRole as FamilyRole,
    displayName: targetMember.displayName ?? undefined,
  };
};
