# Generated by Django 4.2.25 on 2026-06-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_current_value_property_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytransaction',
            name='category',
            field=models.CharField(choices=[('RENT_INCOME', 'Rent Income'), ('MORTGAGE', 'Mortgage'), ('TAXES', 'Taxes'), ('MAINTENANCE', 'Maintenance'), ('INSURANCE', 'Insurance'), ('WATER', 'Water'), ('ELECTRIC', 'Electric'), ('INTERNET', 'Internet'), ('PEST_CONTROL', 'Pest Control'), ('SUPPLIES', 'Supplies'), ('LAWN', 'Lawn Care'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
