# Generated by Django 4.2.25 on 2026-06-19 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0004_historicalpropertytransaction_historicalproperty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('HVAC', 'HVAC'), ('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('ROOFING', 'Roofing'), ('PAINTING', 'Painting'), ('FLOORING', 'Flooring'), ('APPLIANCE', 'Appliance'), ('LANDSCAPING', 'Landscaping'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='planned', max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('contractor_name', models.CharField(blank=True, max_length=200)),
                ('contractor_phone', models.CharField(blank=True, max_length=20)),
                ('contractor_notes', models.TextField(blank=True)),
                ('frequency_months', models.PositiveSmallIntegerField(blank=True, help_text='Repeat interval in months. When marked Completed, a new Planned task is auto-created this many months out.', null=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_projects', to='property.property')),
            ],
            options={
                'ordering': ['due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMaintenanceProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('HVAC', 'HVAC'), ('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('ROOFING', 'Roofing'), ('PAINTING', 'Painting'), ('FLOORING', 'Flooring'), ('APPLIANCE', 'Appliance'), ('LANDSCAPING', 'Landscaping'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='planned', max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('contractor_name', models.CharField(blank=True, max_length=200)),
                ('contractor_phone', models.CharField(blank=True, max_length=20)),
                ('contractor_notes', models.TextField(blank=True)),
                ('frequency_months', models.PositiveSmallIntegerField(blank=True, help_text='Repeat interval in months. When marked Completed, a new Planned task is auto-created this many months out.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prop', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='property.property')),
            ],
            options={
                'verbose_name': 'historical maintenance project',
                'verbose_name_plural': 'historical maintenance projects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
