# Generated by Django 4.2.25 on 2026-07-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_guest_historicalguestbooking_historicalguest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestbooking',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='guestbooking',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='guestbooking',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='historicalguest',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalguestbooking',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='historicalguestbooking',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalguestbooking',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='historicalguestbooking',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='historicalmortgage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmortgage',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='historicalpropertytransaction',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpropertytransaction',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='mortgage',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='propertytransaction',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='purchase_price',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='GuestBooking',
        ),
        migrations.DeleteModel(
            name='HistoricalGuest',
        ),
        migrations.DeleteModel(
            name='HistoricalGuestBooking',
        ),
        migrations.DeleteModel(
            name='HistoricalMortgage',
        ),
        migrations.DeleteModel(
            name='HistoricalPropertyTransaction',
        ),
        migrations.DeleteModel(
            name='Mortgage',
        ),
        migrations.DeleteModel(
            name='PropertyTransaction',
        ),
    ]
