# Generated by Django 4.2.25 on 2026-06-23 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.CharField(blank=True, max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('PRODUCE', 'Produce'), ('MEAT', 'Meat & Seafood'), ('DAIRY', 'Dairy & Eggs'), ('BAKERY', 'Bakery'), ('FROZEN', 'Frozen'), ('PANTRY', 'Pantry'), ('HOUSEHOLD', 'Household'), ('OTHER', 'Other')], default='PANTRY', max_length=20)),
                ('is_purchased', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('source_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_items', to='cookbook.recipe')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
