# Generated by Django 4.2.25 on 2026-06-23 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingitem',
            name='is_purchased',
        ),
    ]
