# Generated by Django 4.2.25 on 2026-07-13 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_family_account_fk'),
        ('shopping', '0002_remove_is_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='core.familyaccount'),
        ),
    ]
